### ISSUE TITLE
Document whether BuildSize works on forks

### ISSUE THREAD

**Issue by edmorley** [Daniel15/BuildSize#29]
One of the downsides to bundlesize is that since it requires that the GitHub token be passed via an environment variable, it doesn't work for PRs opened from forks of a repository (since CI systems like TravisCI strip secure variables for forks). 

Since BuildSize uses a GitHub App, I'm presuming this limitation doesn't apply?

If so, perhaps it would be good to document this in the README and the [comparison page](https://buildsize.org/docs/comparison)?

**Comment by Daniel15** [comment]
PRs via forks work fine, and in fact that's the main scenario I've been
testing (since in open source projects it's more common than PRs directly
on the repo).
