### ISSUE TITLE
When bundle is unaffected, status "no significant change" is misleading

### ISSUE THREAD

**Issue by alexeagle** [Daniel15/BuildSize#35]
"No significant change" makes me wonder if a PR affects the bundle in a subtle way when it should not.

If the bundle is identical, it would be better to report this with a clear message "bundle size is unchanged" or similar.

**Comment by Toxicable** [comment]
This should be an easy fix.
Just add in another check here to see if no change rather than just seeing if it's smaller than `trivial`
https://github.com/Daniel15/BuildSize/blob/d5f12fc661b2236270158cc86ad7d23543b33ed1/app/Listeners/GitHubStatusListener.php#L29

**Comment by alexeagle** [comment]
@Daniel15 are you okay with accepting PRs on this repo? We're using this for Angular now and we're happy to contribute the things we'd like.

**Comment by Daniel15** [comment]
Yeah, I'm happy to accept pull requests! I'm on vacation until Tuesday, but
I can take a look at any PRs once I'm back.
