### ISSUE TITLE
Document what gihub permissions are required

### ISSUE THREAD

**Issue by Toxicable** [Daniel15/BuildSize#37]
It would be great to have added to the developer.md what permissions are required for the app to be registered on Github

**Comment by Daniel15** [comment]
I'm not near my computer at the moment, but I can get this info for you
tomorrow :)

**Comment by Daniel15** [comment]
Added in https://github.com/Daniel15/BuildSize/commit/9320664c2967cfe3a4fb5acdcc74db574c82de3d. Thanks for the suggestion!
