### ISSUE TITLE
BuildSize down?

### ISSUE THREAD

**Issue by wKovacs64** [Daniel15/BuildSize#45]
Hey @Daniel15, is BuildSize still up and running? I noticed the check was missing in a recent PR and when I attempted to login with GitHub (link on buildsize.org), it just says "Whoops, looks like something went wrong." (The network tab of the browser developer tools indicated it was a 500 response from https://d.sb/ if that helps.)

Thanks!

**Comment by Daniel15** [comment]
Interesting, I'll take a look today!

**Comment by Daniel15** [comment]
Sorry about that! I recently switched my server from MariaDB to MySQL 8.x, which apparently had an incompatibility with older Laravel versions (https://github.com/laravel/framework/pull/24038). I bumped the version of Laravel to a newer version, which fixed it. I've been neglecting BuildSize for a while and forgot to test this when switching MySQL version.

**Comment by wKovacs64** [comment]
All good, thanks for the quick fix!
