### ISSUE TITLE
buildsize.org SSL certificate is expired

### ISSUE THREAD

**Issue by wKovacs64** [Daniel15/BuildSize#47]
Looks like it expired back on September 27th, 2019.

**Comment by Daniel15** [comment]
That was really weird since the cert was renewed successfully:
```
% sudo openssl x509 -enddate -noout -in /etc/letsencrypt/live/buildsize.org/cert.pem
notAfter=Nov 27 12:33:38 2019 GMT
```

I just restarted Nginx which worked fine and it picked up the new cert. I suspect Certbot isn't properly reloading Nginx on cert renewal. Will look into it.
